### ISSUE TITLE
Activity streams should be multi-tenant aware

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hybox#110]
The user activity stream shows cross-tenant activity for users that happen to share the same database id.  Possibly look into https://github.com/resque/redis-namespace?

We could also consider refactoring Sufia's activity streams to not use Redis, maybe:

- https://github.com/chaps-io/public_activity
- https://github.com/ledermann/unread

**Comment by mjgiarlo** [comment]
Yes, because of the same database ID.

**Comment by mjgiarlo** [comment]
Note that using public_activity may require modifications to that gem since it only allow tracking mongoid, mongo_mapper, and AR entities at the moment. We'd need to build AF support in.

**Comment by mjgiarlo** [comment]
We assigned this 13 story points on the sprint 6 kick-off meeting this morning.
