### ISSUE TITLE
Implement simplified IIIF presentation support

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hybox#113]
As a depositor, when I upload a single photograph as a new work, it should be available via the IIIF Presentation API. See the [proposed model-to-IIIF mapping](https://github.com/hybox/models/issues/17#issuecomment-196919583). Note that we do not currently use Parts, so we're lacking a Canvas in the current mapping. If helpful, seek advice from @no-reply and @tpendragon and others.

Tentatively scheduled for sprint 6. Blocked by #112.

**Comment by jcoyne** [comment]
Work complete.
