### ISSUE TITLE
Do not check secrets into the repository

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hybox#16]
See: https://github.com/projecthydra-labs/hybox/pull/14/commits/2bfbcf1c8f2674dfe0ff313ba4c8e16f61b56d45

**Comment by cbeer** [comment]
I'd argue it doesn't matter. For local capistrano deploys, it’s a shared file. In AWS (or other 12f apps), it’ll be an env variable.

**Comment by mjgiarlo** [comment]
@cbeer So either way we won't expose any information in said secrets files that can be used against us, in other words? If so, :ok: :+1: #wontfix.

**Comment by cbeer** [comment]
That's the idea.
