### ISSUE TITLE
create data model for image-based works

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hybox#2]
Create a data model in Sufia based on Curation Concerns to enable a depositor to upload an image-based work, along the lines that have been described in user scenarios produced by the Design Team

**Comment by no-reply** [comment]
See also: https://github.com/hybox/models/issues/9

@azaroth42: do we want to schedule a meeting and/or start asynchronous work on this before LDCX?

**Comment by azaroth42** [comment]
I believe I will have time next week to work on this. (Plus a bit of time scattered over the next 2 days)
Let's work asynch for the moment, and see how far we can get. Then try and work through details at LDCX.

@hannahfrost Where would you like questions to be recorded? Issues in hybox/models?

**Comment by jcoyne** [comment]
Done.
