### ISSUE TITLE
CharacterizeJob is not correctly setting mime_type

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hybox#219]
It is being called with a file path, but it probably needs to be called with an S3 url instead.

**Comment by jcoyne** [comment]
Unfortunately it still didn't fix it.

**Comment by jcoyne** [comment]
Working hypothesis: 
The file set has the wrong object, so when it's reindexed here, it doesn't know the mime type is updated
https://github.com/projecthydra/curation_concerns/blob/master/app/jobs/characterize_job.rb#L12

**Comment by jcoyne** [comment]
https://gist.github.com/jcoyne/a0d2244da4c65db890ce8e191eba26a1

It looks like the mime-type just isn't being persisted.

**Comment by jcoyne** [comment]
I think it's related to https://github.com/projecthydra/active_fedora/pull/1091

**Comment by mjgiarlo** [comment]
@jcoyne do we think this is fixed in HyBox now?

**Comment by jcoyne** [comment]
Yep.
